# Generated by Django 5.2.17 on 2026-09-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Cashfree Payment Session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reference',
            field=models.CharField(blank=True, help_text='Cashfree Refund ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, help_text='Cashfree / Gateway Order ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, help_text='Cashfree Payment ID (cf_payment_id)', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_provider',
            field=models.CharField(default='CASHFREE', help_text='SANDBOX, CASHFREE', max_length=50),
        ),
    ]
