# Generated by Django 5.2.17 on 2026-09-13 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, help_text='Short description from real menu (optional)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck when sold out')),
                ('spice_level', models.PositiveSmallIntegerField(default=0, help_text='Number of chilis (0-3) for spicy items')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
            ],
            options={
                'ordering': ['category__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_type', models.CharField(choices=[('SAUCE', 'Momo Sauce / Preparation'), ('WAFFLE', 'Waffle Add-On'), ('GENERAL', 'General Add-On')], default='SAUCE', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('spice_level', models.PositiveSmallIntegerField(default=0, help_text='Spice level (0-3)')),
                ('applicable_items', models.ManyToManyField(blank=True, help_text='Menu items that this sauce/add-on can be added to', related_name='applicable_addons', to='menu.menuitem')),
            ],
            options={
                'ordering': ['category_type', 'price', 'name'],
            },
        ),
    ]
