# Generated by Django 5.2.17 on 2026-09-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
