# Generated by Django 5.2.17 on 2026-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ready_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
