# Generated by Django 5.2.17 on 2026-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_email_sent_order_payment_email_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ready_sms_sent',
        ),
    ]
