# Generated by Django 5.2.17 on 2026-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('message_type', models.CharField(choices=[('CONFIRMATION', 'Order Confirmation'), ('READY', 'Order Ready for Pickup'), ('REFUND', 'Order Refund / Closure')], default='CONFIRMATION', max_length=20)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('SIMULATED', 'Simulated / Logged')], default='SIMULATED', max_length=20)),
                ('provider', models.CharField(default='CONSOLE', max_length=50)),
                ('provider_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
