# Generated by Django 5.2.17 on 2026-10-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('TEST', 'Test Email'), ('ORDER_CREATED', 'Order Created / Pre-booking'), ('PAYMENT_SUCCESS', 'Payment Successful'), ('READY', 'Order Ready for Pickup'), ('REFUND', 'Order Refund / Closure')], default='ORDER_CREATED', max_length=30)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
