# Generated by Django 5.2.17 on 2026-10-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (No Email / Duplicate)')], default='SENT', max_length=20),
        ),
    ]
