# Generated by Django 5.2.17 on 2026-10-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emaillog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
